### ISSUE TITLE
Invocation of non-function in source/views/stoprint/print-jobs.tsx

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#5236]
I'm going to need some help from @hawkrives on this one, I think!

LGTM found a "Callee is not a function: it has type `undefined`" correctness hole:

https://lgtm.com/projects/g/StoDevX/AAO-React-Native/snapshot/58f99f6ef922ebb9223429ccf424aa0bfdb491b3/files/source/views/stoprint/print-jobs.tsx

It seems to think I introduced this in 670c2cb47a79ddbb9e733563cdd267e1f1f976ad, but I think the underlying issue was introduced in d4f7d819072b2f435c389b1543f2dab22814f544 with the original addition of the `_logInViaCredentials`, and it just surfaced with the additional restrictions imposed by TypeScript.

Sure enough, when I launch up the StoPrint view, the app is stuck on the "Fetching a list of stoPrint Jobs..." view, which seems to me to indicate that this log in is never succeeding.

**Comment by hawkrives** [comment]
Just to check, you're connected to the Stolaf VPN?

**Comment by rye** [comment]
Nope, lol... maybe I should be!

**Comment by rye** [comment]
In Settings > Debug, `login` > `status` is `"logged-in"`, FWIW.

**Comment by rye** [comment]
This also just came through on Sentry:

![Screenshot from 2021-07-18 14-02-25](https://user-images.githubusercontent.com/1566689/126079255-9b9b16b7-c85e-469e-b475-2249ab43238d.png)

**Comment by drewvolz** [comment]
@rye do you see the same outcome after resetting the app and then connecting when on the VPN?

**Comment by rye** [comment]
I do get a Connection Issue screen instead of a Fetching screen if I first open settings.

If I reset the app, I'm prompted to log in. If I log in and then go to the stoPrint screen, I get Connection Issue.  It's only after the app restarts that this fails, it seems. Force stopping, my login state isn't preserved, but I guess I'd kinda expect the stoPrint screen to do that for me

**Comment by hawkrives** [comment]
@drewvolz @rye Do you think this one is still valid? All of the credential handling has been reworked now…

**Comment by drewvolz** [comment]
Feel free to close this and we will handle it if Sentry sees it again.
